name: Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Use Node 18.x
              uses: actions/setup-node@main
              with:
                  node-version: "18.x"

            - name: Run npm install
              run: npm i

            - name: Run test CI command
              run: npm run test:ci

            - name: Check if code coverage was made
              id: check_files
              uses: andstor/file-existence-action@main
              with:
                  files: "coverage"

            - name: Archive code coverage if it was made
              if: success() && steps.check_files.outputs.files_exists == 'true'
              uses: actions/upload-artifact@main
              with:
                  name: deploy_coverage
                  path: coverage
